version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: documents-worker-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  documents-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: documents-worker-app
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - ENVIRONMENT=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - WORKER_MAX_CONCURRENCY=5
      - WORKER_QUEUE_NAME=documents_queue
      - WORKER_RETRY_COUNT=3
      - WORKER_RETRY_DELAY=5s
      - VIPS_ENABLED=true
      - OCR_LANGUAGE=tur+eng
      - OCR_DPI=300
      - OCR_PSM=1
    volumes:
      - /tmp:/tmp
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health/liveness"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  redis_data:
